version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    volumes:
      - .:/usr/src/app
    environment:
      - NAME=World
    command: python bot.py
